### ISSUE TITLE
Bug: Adjustion of dataAdress type in UI

### ISSUE THREAD

**Issue by lenasauermann** [GAIA-X4PLC-AAD/EDC-Blockchain-Dashboard#36]
The dashboard does not allow to select configured dataAdress types when creating an asset, particulary "AzureStorage".

Dmi said this is possible here https://github.com/eclipse-edc/DataDashboard/tree/main so we propably need to look what is different in our version.

AzureStorage Extension is described here https://github.com/eclipse-edc/Technology-Azure/tree/main/extensions/data-plane/data-plane-azure-storage

JSON should look like this:

{
    "asset": {
        "properties": {
            "asset:prop:name": "{{asset_guid}}",
            "asset:prop:contenttype": "text/plain",
            "asset:prop:version": "1.0",
            "asset:prop:id": "{{asset_guid}}",
            "type": "AzureStorage"
        }
    },
    "dataAddress": {
        "properties": {
            "type": "AzureStorage",
            "account": "msgedcstorage",
            "container": "src-container",
            "blobname": "{{document_name}}",
            "keyName": "msgedcstorage-key1"
        }
    }
}

**Comment by robertschubert** [comment]
I am starting to enable the AzureStorage in our setup
